import { Html, Head, Main, NextScript } from 'next/document';
import Script from 'next/script';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <Script
          id={'pp-variables'}
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.PP_VARIABLES = {
            TEST: '[Data Classification]',
          }`,
          }}
        ></Script>
        <NextScript />
      </body>
    </Html>
  );
}
