name: Publish Package

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "create-pp-dev*" # # Push events to matching create-pp-dev*, i.e. create-pp-dev@1.0.0

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'mi-examples/pp-dev-js'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Get pkgName for publish
        id: tag
        run: |
          # matching v2.0.0 / v2.0.0-beta.8 etc
          if [[ $GITHUB_REF_NAME =~ ^v.+ ]]; then
            pkgName="pp-dev"
          else
            # `%@*` truncates @ and version number from the right side.
            # https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
            pkgName=${GITHUB_REF_NAME%@*}
          fi
          
          echo "pkgName=$pkgName" >> $GITHUB_OUTPUT

      - name: Install deps
        working-directory: ./packages/${{ steps.tag.outputs.pkgName }}
        run: npm install
        
      - name: Build package
        working-directory: ./packages/${{ steps.tag.outputs.pkgName }}
        run: npm run build

      - name: Publish package
        working-directory: ./packages/${{ steps.tag.outputs.pkgName }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
